/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CommentId = IDL.Text;
export const Timestamp = IDL.Int;
export const PostId = IDL.Text;
export const Comment = IDL.Record({
  'id' : CommentId,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : Timestamp,
  'postId' : PostId,
});
export const GroupId = IDL.Text;
export const Group = IDL.Record({
  'id' : GroupId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'memberCount' : IDL.Nat,
  'creatorId' : IDL.Principal,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const GroupPost = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : Timestamp,
  'imageUrl' : IDL.Opt(IDL.Text),
  'groupId' : GroupId,
});
export const Post = IDL.Record({
  'id' : PostId,
  'likeCount' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : Timestamp,
  'imageUrl' : IDL.Opt(IDL.Text),
  'commentCount' : IDL.Nat,
});
export const StoryId = IDL.Text;
export const Story = IDL.Record({
  'id' : StoryId,
  'content' : IDL.Opt(IDL.Text),
  'expiresAt' : Timestamp,
  'authorId' : IDL.Principal,
  'createdAt' : Timestamp,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'isSuspended' : IDL.Bool,
  'isAdmin' : IDL.Bool,
});
export const MessageId = IDL.Text;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'receiverId' : IDL.Principal,
  'senderId' : IDL.Principal,
});
export const Conversation = IDL.Record({
  'otherUserId' : IDL.Principal,
  'lastMessage' : IDL.Opt(Message),
  'unreadCount' : IDL.Nat,
});
export const ReportId = IDL.Text;
export const Report = IDL.Record({
  'id' : ReportId,
  'contentId' : IDL.Text,
  'contentType' : IDL.Text,
  'isReviewed' : IDL.Bool,
  'createdAt' : Timestamp,
  'reporterId' : IDL.Principal,
  'details' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'isSuspended' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'isAdmin' : IDL.Bool,
  'followingCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Comment, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteComment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeletePost' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createGroup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Group, 'err' : IDL.Text })],
      [],
    ),
  'createGroupPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : GroupPost, 'err' : IDL.Text })],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Post, 'err' : IDL.Text })],
      [],
    ),
  'createStory' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Story, 'err' : IDL.Text })],
      [],
    ),
  'deleteComment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deletePost' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'dismissReport' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'followUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingReports' : IDL.Nat,
          'totalReports' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalPosts' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getExplorePosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFeedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(Group)], ['query']),
  'getGroupMembers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getGroupPosts' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(GroupPost)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getMyStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getUserPosts' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasLikedPost' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'isGroupMember' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'leaveGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'likePost' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'reportContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Report, 'err' : IDL.Text })],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'setAdmin' : IDL.Func(
      [IDL.Principal, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'suspendUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unfollowUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unlikePost' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'unsuspendUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CommentId = IDL.Text;
  const Timestamp = IDL.Int;
  const PostId = IDL.Text;
  const Comment = IDL.Record({
    'id' : CommentId,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : Timestamp,
    'postId' : PostId,
  });
  const GroupId = IDL.Text;
  const Group = IDL.Record({
    'id' : GroupId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'memberCount' : IDL.Nat,
    'creatorId' : IDL.Principal,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const GroupPost = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : Timestamp,
    'imageUrl' : IDL.Opt(IDL.Text),
    'groupId' : GroupId,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'likeCount' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : Timestamp,
    'imageUrl' : IDL.Opt(IDL.Text),
    'commentCount' : IDL.Nat,
  });
  const StoryId = IDL.Text;
  const Story = IDL.Record({
    'id' : StoryId,
    'content' : IDL.Opt(IDL.Text),
    'expiresAt' : Timestamp,
    'authorId' : IDL.Principal,
    'createdAt' : Timestamp,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'isSuspended' : IDL.Bool,
    'isAdmin' : IDL.Bool,
  });
  const MessageId = IDL.Text;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'receiverId' : IDL.Principal,
    'senderId' : IDL.Principal,
  });
  const Conversation = IDL.Record({
    'otherUserId' : IDL.Principal,
    'lastMessage' : IDL.Opt(Message),
    'unreadCount' : IDL.Nat,
  });
  const ReportId = IDL.Text;
  const Report = IDL.Record({
    'id' : ReportId,
    'contentId' : IDL.Text,
    'contentType' : IDL.Text,
    'isReviewed' : IDL.Bool,
    'createdAt' : Timestamp,
    'reporterId' : IDL.Principal,
    'details' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'isSuspended' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'isAdmin' : IDL.Bool,
    'followingCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Comment, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteComment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeletePost' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createGroup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Group, 'err' : IDL.Text })],
        [],
      ),
    'createGroupPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : GroupPost, 'err' : IDL.Text })],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Post, 'err' : IDL.Text })],
        [],
      ),
    'createStory' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Story, 'err' : IDL.Text })],
        [],
      ),
    'deleteComment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deletePost' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'dismissReport' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'followUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingReports' : IDL.Nat,
            'totalReports' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalPosts' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getExplorePosts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getFeedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(Group)], ['query']),
    'getGroupMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGroupPosts' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(GroupPost)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getMyStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getUserPosts' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasLikedPost' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isGroupMember' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'leaveGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'likePost' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'reportContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Report, 'err' : IDL.Text })],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'setAdmin' : IDL.Func(
        [IDL.Principal, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'suspendUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unfollowUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unlikePost' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'unsuspendUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };