/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'isDeleted' : boolean,
  'content' : string,
  'authorId' : Principal,
  'createdAt' : Timestamp,
  'postId' : PostId,
}
export type CommentId = string;
export interface Conversation {
  'otherUserId' : Principal,
  'lastMessage' : [] | [Message],
  'unreadCount' : bigint,
}
export interface Group {
  'id' : GroupId,
  'name' : string,
  'createdAt' : Timestamp,
  'memberCount' : bigint,
  'creatorId' : Principal,
  'description' : string,
  'category' : string,
}
export type GroupId = string;
export interface GroupPost {
  'id' : string,
  'content' : string,
  'authorId' : Principal,
  'createdAt' : Timestamp,
  'imageUrl' : [] | [string],
  'groupId' : GroupId,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'receiverId' : Principal,
  'senderId' : Principal,
}
export type MessageId = string;
export interface Post {
  'id' : PostId,
  'likeCount' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'authorId' : Principal,
  'createdAt' : Timestamp,
  'imageUrl' : [] | [string],
  'commentCount' : bigint,
}
export type PostId = string;
export interface Report {
  'id' : ReportId,
  'contentId' : string,
  'contentType' : string,
  'isReviewed' : boolean,
  'createdAt' : Timestamp,
  'reporterId' : Principal,
  'details' : [] | [string],
  'reason' : string,
}
export type ReportId = string;
export interface Story {
  'id' : StoryId,
  'content' : [] | [string],
  'expiresAt' : Timestamp,
  'authorId' : Principal,
  'createdAt' : Timestamp,
  'imageUrl' : [] | [string],
}
export type StoryId = string;
export type Timestamp = bigint;
export interface User {
  'id' : Principal,
  'bio' : string,
  'username' : string,
  'createdAt' : Timestamp,
  'avatarUrl' : [] | [string],
  'isSuspended' : boolean,
  'isAdmin' : boolean,
}
export interface UserProfile {
  'id' : Principal,
  'bio' : string,
  'postCount' : bigint,
  'username' : string,
  'createdAt' : Timestamp,
  'avatarUrl' : [] | [string],
  'isSuspended' : boolean,
  'followerCount' : bigint,
  'isAdmin' : boolean,
  'followingCount' : bigint,
}
export interface _SERVICE {
  'addComment' : ActorMethod<
    [string, string],
    { 'ok' : Comment } |
      { 'err' : string }
  >,
  'adminDeleteComment' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeletePost' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createGroup' : ActorMethod<
    [string, string, string],
    { 'ok' : Group } |
      { 'err' : string }
  >,
  'createGroupPost' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : GroupPost } |
      { 'err' : string }
  >,
  'createPost' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : Post } |
      { 'err' : string }
  >,
  'createStory' : ActorMethod<
    [[] | [string], [] | [string]],
    { 'ok' : Story } |
      { 'err' : string }
  >,
  'deleteComment' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'deleteGroup' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'deletePost' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'dismissReport' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'followUser' : ActorMethod<[Principal], { 'ok' : null } | { 'err' : string }>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'pendingReports' : bigint,
      'totalReports' : bigint,
      'totalUsers' : bigint,
      'totalPosts' : bigint,
    }
  >,
  'getAllActiveStories' : ActorMethod<[], Array<Story>>,
  'getAllGroups' : ActorMethod<[], Array<Group>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getExplorePosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFeedPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getGroup' : ActorMethod<[string], [] | [Group]>,
  'getGroupMembers' : ActorMethod<[string], Array<Principal>>,
  'getGroupPosts' : ActorMethod<[string, bigint, bigint], Array<GroupPost>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getMyStories' : ActorMethod<[], Array<Story>>,
  'getPost' : ActorMethod<[string], [] | [Post]>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserGroups' : ActorMethod<[], Array<Group>>,
  'getUserPosts' : ActorMethod<[Principal, bigint, bigint], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasLikedPost' : ActorMethod<[string], boolean>,
  'isFollowing' : ActorMethod<[Principal, Principal], boolean>,
  'isGroupMember' : ActorMethod<[string], boolean>,
  'joinGroup' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'leaveGroup' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'likePost' : ActorMethod<[string], { 'ok' : bigint } | { 'err' : string }>,
  'markMessagesRead' : ActorMethod<[Principal], undefined>,
  'registerUser' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : User } |
      { 'err' : string }
  >,
  'reportContent' : ActorMethod<
    [string, string, string, [] | [string]],
    { 'ok' : Report } |
      { 'err' : string }
  >,
  'sendMessage' : ActorMethod<
    [Principal, string],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'setAdmin' : ActorMethod<
    [Principal, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'suspendUser' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unfollowUser' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unlikePost' : ActorMethod<[string], { 'ok' : bigint } | { 'err' : string }>,
  'unsuspendUser' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : User } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];