/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type CommentId = string;
export interface Comment {
    id: CommentId;
    isDeleted: boolean;
    content: string;
    authorId: Principal;
    createdAt: Timestamp;
    postId: PostId;
}
export interface User {
    id: Principal;
    bio: string;
    username: string;
    createdAt: Timestamp;
    avatarUrl?: string;
    isSuspended: boolean;
    isAdmin: boolean;
}
export interface Story {
    id: StoryId;
    content?: string;
    expiresAt: Timestamp;
    authorId: Principal;
    createdAt: Timestamp;
    imageUrl?: string;
}
export type StoryId = string;
export type PostId = string;
export interface Group {
    id: GroupId;
    name: string;
    createdAt: Timestamp;
    memberCount: bigint;
    creatorId: Principal;
    description: string;
    category: string;
}
export interface Report {
    id: ReportId;
    contentId: string;
    contentType: string;
    isReviewed: boolean;
    createdAt: Timestamp;
    reporterId: Principal;
    details?: string;
    reason: string;
}
export type GroupId = string;
export type ReportId = string;
export type MessageId = string;
export interface Post {
    id: PostId;
    likeCount: bigint;
    isDeleted: boolean;
    content: string;
    authorId: Principal;
    createdAt: Timestamp;
    imageUrl?: string;
    commentCount: bigint;
}
export interface GroupPost {
    id: string;
    content: string;
    authorId: Principal;
    createdAt: Timestamp;
    imageUrl?: string;
    groupId: GroupId;
}
export interface Message {
    id: MessageId;
    content: string;
    createdAt: Timestamp;
    isRead: boolean;
    receiverId: Principal;
    senderId: Principal;
}
export interface Conversation {
    otherUserId: Principal;
    lastMessage?: Message;
    unreadCount: bigint;
}
export interface UserProfile {
    id: Principal;
    bio: string;
    postCount: bigint;
    username: string;
    createdAt: Timestamp;
    avatarUrl?: string;
    isSuspended: boolean;
    followerCount: bigint;
    isAdmin: boolean;
    followingCount: bigint;
}
export interface backendInterface {
    addComment(postId: string, content: string): Promise<{
        __kind__: "ok";
        ok: Comment;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteComment(commentId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeletePost(postId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createGroup(name: string, description: string, category: string): Promise<{
        __kind__: "ok";
        ok: Group;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createGroupPost(groupId: string, content: string, imageUrl: string | null): Promise<{
        __kind__: "ok";
        ok: GroupPost;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createPost(content: string, imageUrl: string | null): Promise<{
        __kind__: "ok";
        ok: Post;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createStory(content: string | null, imageUrl: string | null): Promise<{
        __kind__: "ok";
        ok: Story;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteComment(commentId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteGroup(groupId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deletePost(postId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    dismissReport(reportId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    followUser(targetId: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActiveStories(): Promise<Array<Story>>;
    getAdminStats(): Promise<{
        pendingReports: bigint;
        totalReports: bigint;
        totalUsers: bigint;
        totalPosts: bigint;
    }>;
    getAllActiveStories(): Promise<Array<Story>>;
    getAllGroups(): Promise<Array<Group>>;
    getAllPosts(): Promise<Array<Post>>;
    getAllUsers(): Promise<Array<User>>;
    getComments(postId: string): Promise<Array<Comment>>;
    getConversations(): Promise<Array<Conversation>>;
    getExplorePosts(limit: bigint, offset: bigint): Promise<Array<Post>>;
    getFeedPosts(limit: bigint, offset: bigint): Promise<Array<Post>>;
    getFollowers(userId: Principal): Promise<Array<Principal>>;
    getFollowing(userId: Principal): Promise<Array<Principal>>;
    getGroup(groupId: string): Promise<Group | null>;
    getGroupMembers(groupId: string): Promise<Array<Principal>>;
    getGroupPosts(groupId: string, limit: bigint, offset: bigint): Promise<Array<GroupPost>>;
    getMessages(otherUserId: Principal): Promise<Array<Message>>;
    getMyStories(): Promise<Array<Story>>;
    getPost(postId: string): Promise<Post | null>;
    getReports(): Promise<Array<Report>>;
    getUnreadCount(): Promise<bigint>;
    getUser(userId: Principal): Promise<User | null>;
    getUserGroups(): Promise<Array<Group>>;
    getUserPosts(userId: Principal, limit: bigint, offset: bigint): Promise<Array<Post>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    hasLikedPost(postId: string): Promise<boolean>;
    isFollowing(userId: Principal, targetId: Principal): Promise<boolean>;
    isGroupMember(groupId: string): Promise<boolean>;
    joinGroup(groupId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    leaveGroup(groupId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    likePost(postId: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    markMessagesRead(otherUserId: Principal): Promise<void>;
    registerUser(username: string, bio: string, avatarUrl: string | null): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
    reportContent(contentType: string, contentId: string, reason: string, details: string | null): Promise<{
        __kind__: "ok";
        ok: Report;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendMessage(receiverId: Principal, content: string): Promise<{
        __kind__: "ok";
        ok: Message;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAdmin(userId: Principal, isAdminFlag: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    suspendUser(userId: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unfollowUser(targetId: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unlikePost(postId: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unsuspendUser(userId: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProfile(username: string, bio: string, avatarUrl: string | null): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Comment as _Comment, Conversation as _Conversation, Group as _Group, GroupId as _GroupId, GroupPost as _GroupPost, Message as _Message, Post as _Post, PostId as _PostId, Report as _Report, ReportId as _ReportId, Story as _Story, StoryId as _StoryId, Timestamp as _Timestamp, User as _User, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: Comment;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteComment(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteComment(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteComment(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeletePost(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeletePost(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeletePost(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGroup(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Group;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGroupPost(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: GroupPost;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroupPost(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroupPost(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: string, arg1: string | null): Promise<{
        __kind__: "ok";
        ok: Post;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStory(arg0: string | null, arg1: string | null): Promise<{
        __kind__: "ok";
        ok: Story;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(to_candid_opt_n4(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(to_candid_opt_n4(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGroup(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePost(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async dismissReport(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissReport(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissReport(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async followUser(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStories();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStories();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<{
        pendingReports: bigint;
        totalReports: bigint;
        totalUsers: bigint;
        totalPosts: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllActiveStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveStories();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveStories();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroups();
            return result;
        }
    }
    async getAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExplorePosts(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExplorePosts(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExplorePosts(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedPosts(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedPosts(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedPosts(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getGroup(arg0: string): Promise<Group | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroup(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroup(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMembers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMembers(arg0);
            return result;
        }
    }
    async getGroupPosts(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<GroupPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupPosts(arg0, arg1, arg2);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupPosts(arg0, arg1, arg2);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStories();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStories();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: string): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserGroups();
            return result;
        }
    }
    async getUserPosts(arg0: Principal, arg1: bigint, arg2: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPosts(arg0, arg1, arg2);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPosts(arg0, arg1, arg2);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasLikedPost(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasLikedPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasLikedPost(arg0);
            return result;
        }
    }
    async isFollowing(arg0: Principal, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0, arg1);
            return result;
        }
    }
    async isGroupMember(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isGroupMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isGroupMember(arg0);
            return result;
        }
    }
    async joinGroup(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGroup(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGroup(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveGroup(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async likePost(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async markMessagesRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async reportContent(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<{
        __kind__: "ok";
        ok: Report;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reportContent(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportContent(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<{
        __kind__: "ok";
        ok: Message;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdmin(arg0: Principal, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async suspendUser(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfollowUser(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlikePost(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async unsuspendUser(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unsuspendUser(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsuspendUser(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Conversation_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_GroupPost_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupPost): GroupPost {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Story_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Story {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_User_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Group]): Group | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    likeCount: bigint;
    isDeleted: boolean;
    content: string;
    authorId: Principal;
    createdAt: _Timestamp;
    imageUrl: [] | [string];
    commentCount: bigint;
}): {
    id: PostId;
    likeCount: bigint;
    isDeleted: boolean;
    content: string;
    authorId: Principal;
    createdAt: Timestamp;
    imageUrl?: string;
    commentCount: bigint;
} {
    return {
        id: value.id,
        likeCount: value.likeCount,
        isDeleted: value.isDeleted,
        content: value.content,
        authorId: value.authorId,
        createdAt: value.createdAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.imageUrl)),
        commentCount: value.commentCount
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StoryId;
    content: [] | [string];
    expiresAt: _Timestamp;
    authorId: Principal;
    createdAt: _Timestamp;
    imageUrl: [] | [string];
}): {
    id: StoryId;
    content?: string;
    expiresAt: Timestamp;
    authorId: Principal;
    createdAt: Timestamp;
    imageUrl?: string;
} {
    return {
        id: value.id,
        content: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.content)),
        expiresAt: value.expiresAt,
        authorId: value.authorId,
        createdAt: value.createdAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.imageUrl))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    username: string;
    createdAt: _Timestamp;
    avatarUrl: [] | [string];
    isSuspended: boolean;
    isAdmin: boolean;
}): {
    id: Principal;
    bio: string;
    username: string;
    createdAt: Timestamp;
    avatarUrl?: string;
    isSuspended: boolean;
    isAdmin: boolean;
} {
    return {
        id: value.id,
        bio: value.bio,
        username: value.username,
        createdAt: value.createdAt,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.avatarUrl)),
        isSuspended: value.isSuspended,
        isAdmin: value.isAdmin
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    otherUserId: Principal;
    lastMessage: [] | [_Message];
    unreadCount: bigint;
}): {
    otherUserId: Principal;
    lastMessage?: Message;
    unreadCount: bigint;
} {
    return {
        otherUserId: value.otherUserId,
        lastMessage: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.lastMessage)),
        unreadCount: value.unreadCount
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReportId;
    contentId: string;
    contentType: string;
    isReviewed: boolean;
    createdAt: _Timestamp;
    reporterId: Principal;
    details: [] | [string];
    reason: string;
}): {
    id: ReportId;
    contentId: string;
    contentType: string;
    isReviewed: boolean;
    createdAt: Timestamp;
    reporterId: Principal;
    details?: string;
    reason: string;
} {
    return {
        id: value.id,
        contentId: value.contentId,
        contentType: value.contentType,
        isReviewed: value.isReviewed,
        createdAt: value.createdAt,
        reporterId: value.reporterId,
        details: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.details)),
        reason: value.reason
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    postCount: bigint;
    username: string;
    createdAt: _Timestamp;
    avatarUrl: [] | [string];
    isSuspended: boolean;
    followerCount: bigint;
    isAdmin: boolean;
    followingCount: bigint;
}): {
    id: Principal;
    bio: string;
    postCount: bigint;
    username: string;
    createdAt: Timestamp;
    avatarUrl?: string;
    isSuspended: boolean;
    followerCount: bigint;
    isAdmin: boolean;
    followingCount: bigint;
} {
    return {
        id: value.id,
        bio: value.bio,
        postCount: value.postCount,
        username: value.username,
        createdAt: value.createdAt,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.avatarUrl)),
        isSuspended: value.isSuspended,
        followerCount: value.followerCount,
        isAdmin: value.isAdmin,
        followingCount: value.followingCount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    authorId: Principal;
    createdAt: _Timestamp;
    imageUrl: [] | [string];
    groupId: _GroupId;
}): {
    id: string;
    content: string;
    authorId: Principal;
    createdAt: Timestamp;
    imageUrl?: string;
    groupId: GroupId;
} {
    return {
        id: value.id,
        content: value.content,
        authorId: value.authorId,
        createdAt: value.createdAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.imageUrl)),
        groupId: value.groupId
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Comment;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Comment;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Story;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Story;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Story_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Group;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Group;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n18(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Report;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Report;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Report_n28(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Message;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Message;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GroupPost;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GroupPost;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GroupPost_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Post;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Post;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Post_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Array<Story> {
    return value.map((x)=>from_candid_Story_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupPost>): Array<GroupPost> {
    return value.map((x)=>from_candid_GroupPost_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n28(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
